---
title: "FinalProject"
author: "Group 30"
date: "2022-11-28"
output: github_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(knitr.duplicate.label = "allow")

```

## R Markdown

```{r, include=FALSE}
library(ggplot2)
#library(plot3D)
library(tidyverse)
library(dplyr)
library(MASS)
library(car)
library(caret)
library(glmnet)
```


### Appendix 1: Distribution of Data

```{r} 
Body_df = readxl::read_excel("data/body_density_data.xlsx")
summary(Body_df)


#the data is all continuous so histogram

ggplot(Body_df, aes(x=bodyfat_brozek)) + 
 geom_histogram(aes(y=..density..), colour="black", fill="white",binwidth = 1)+
 geom_density(alpha=.2)+
 labs(title="Distributions of body fat measured in Brozek method")



#define column names
colnames = colnames(Body_df)

# Predictor:
for (i in 5:length(colnames)){
  plot = 
ggplot(Body_df, aes_string(x=colnames[i])) + 
 geom_histogram(aes(y=..density..), colour="black", fill="white",binwidth = 1)+
 geom_density(alpha=.2)+
 labs(title=sprintf("Distributions of %s", colnames[i]) )
  
  print(plot)
}


```


### Appendix 2: Scatter Plot


```{r,message = FALSE, warning = FALSE}



for (i in 5:length(colnames)){
  plot = 
  Body_df %>% 
    ggplot(aes_string(x = colnames[i], y = "bodyfat_brozek"))+geom_point()+geom_smooth(method = 'lm', se = TRUE, color = 'red')+
    labs(title = sprintf("Scatter plot for body fat against %s", colnames[i]) )+
    ylab("Body Fat (Brozek)")
  
  print(plot)
}





```


### Appendix 3: Variable Selection VIF
Using Backwards only

```{r}

bodyfat_temp = 
  Body_df %>% 
  dplyr::select(-id,-bodyfat_siri,-body_density)
  
  
# Fit the full model 
Full_model <- lm(bodyfat_brozek ~., data = bodyfat_temp)

vif(Full_model)

bodyfat_noweight = 
  bodyfat_temp %>% 
  dplyr::select(-"weight")

Weight_removed_model <- lm(bodyfat_brozek ~., data = bodyfat_noweight)

vif(Weight_removed_model)

bodyfat_noabdweight=
  bodyfat_temp %>% 
  dplyr::select(-"weight",-"abdomen")

abd_weight_removed <- lm(bodyfat_brozek ~., data = bodyfat_noabdweight)
vif(abd_weight_removed)

```

### Appendix 3: Model Selection using backward with cv


```{r}
bodyfat_temp =
  bodyfat_temp %>% 
  dplyr::select(-abdomen, -weight)


# Set seed for reproducibility
set.seed(123)
# Set up repeated k-fold cross-validation
train.control <- trainControl(method = "cv", number = 10)
# Train the model
step.model <- train(bodyfat_brozek ~., data = bodyfat_temp,
                    method = "leapBackward", 
                    tuneGrid = data.frame(nvmax = 1:5),
                    trControl = train.control
                    )
step.model$results
summary(step.model$finalModel)
```

```{r}
Selected_lm_model = lm(bodyfat_brozek~age+height+chest+thigh+wrist, data = bodyfat_temp)

plot(Selected_lm_model)
summary(Selected_lm_model)
```


### Appendix 4 Log transformation
```{r}
bodyfat_nonzero = 
  bodyfat_temp %>% 
  filter(bodyfat_brozek!=0) 

bodyfat_log = 
  bodyfat_nonzero %>% 
  mutate(log_bodyfat_brozek=log(bodyfat_brozek))
  
  
boxcox_lm_model = lm(log_bodyfat_brozek~age+height+chest+thigh+wrist, data = bodyfat_log)

plot(boxcox_lm_model)
summary(boxcox_lm_model)
```


### Appendix 5 Box Cox

#### All

```{r}

mylm_all = lm(bodyfat_brozek~., data = bodyfat_nonzero)
bc_mod_all = boxcox(mylm_all)
lambda <- bc_mod_all$x[which.max(bc_mod_all$y)]

new_model_all <- lm(((bodyfat_brozek^lambda-1)/lambda) ~ ., data = bodyfat_nonzero)

stepsearch_coxall=step(new_model_all)

step_cox = lm(formula = ((bodyfat_brozek^lambda - 1)/lambda) ~ age + height + chest + 
    hip + thigh + wrist, data = bodyfat_nonzero)

plot(step_cox)
summary(step_cox)
AIC(step_cox)
```

```{r}
#lambda = 1 case
step_cox_1 = lm(formula = ((bodyfat_brozek^1 - 1)/1) ~ age + height + chest + 
    hip + thigh + wrist, data = bodyfat_nonzero)

plot(step_cox_1)
summary(step_cox_1)
AIC(step_cox_1)
```


#### Partial

```{r}

#chosen from previous model 

mylm = lm(bodyfat_brozek~age+height+chest+thigh+wrist, data = bodyfat_nonzero)
bc_mod = boxcox(mylm)
lambda <- bc_mod$x[which.max(bc_mod$y)]

new_model <- lm(((bodyfat_brozek^lambda-1)/lambda) ~ age+height+chest+thigh+wrist, data = bodyfat_nonzero)

plot(new_model)
summary(new_model)
AIC(new_model)
```

```{r}
#lambda = 1 case
new_model_1 <- lm(((bodyfat_brozek^1-1)/1) ~ age+height+chest+thigh+wrist, data = bodyfat_nonzero)

plot(new_model_1)
summary(new_model_1)
AIC(new_model_1)
```





### Appendix 6 Pairwise

```{r}
lm0 = lm(bodyfat_brozek~age+height+chest+thigh+wrist, data = bodyfat_temp)

stepsearch = step(lm0,~.^2)

```

```{r}
lm_pairwise = lm(bodyfat_brozek~age + height + chest + thigh + wrist + thigh:wrist + 
    age:wrist + height:chest, data = bodyfat_temp)

plot(lm_pairwise)
summary(lm_pairwise)
```

### Appendix 7 Square term

```{r}
square_lm = lm(bodyfat_brozek ~ poly(age,2)+poly(height,2)+poly(chest,2)+poly(thigh, 2)+poly(wrist,2), data=Body_df)

step(square_lm)

#square_lm_adpt = lm(bodyfat_brozek~poly(abdomen, 2) + poly(wrist, 2) + poly(weight,2),data=Body_df)

plot(square_lm)
summary(square_lm)
```


### Appendix 8 Lasso 

#### All Var
```{r}
set.seed(100)
#all weight
bodyfat_temp_all = 
  Body_df %>% 
  dplyr::select(-id,-bodyfat_siri,-body_density)

lambda_seq <- 10^seq(-3, 0, by = .1)
cv_object <- cv.glmnet(as.matrix(bodyfat_temp_all[,-1]), bodyfat_temp_all$bodyfat_brozek, lambda = lambda_seq, 
nfolds = 5)
cv_object

tibble(lambda = cv_object$lambda,
mean_cv_error = cv_object$cvm) %>%
ggplot(aes(x = lambda, y = 
mean_cv_error)) +
geom_point()
cv_object$lambda.min
```



```{r}
fit_bestcv <- glmnet(as.matrix(bodyfat_temp_all[,-1]), bodyfat_temp_all$bodyfat_brozek, lambda = cv_object$lambda.min)
best_lambda = cv_object$lambda.min
coef(fit_bestcv)

set.seed(100)
# Use 5-fold validation and create the training sets
train = trainControl(method = "cv", number = 5)
# Fit the variables model 
model_caret = train(bodyfat_brozek ~ age + weight+ height + neck + abdomen +hip+thigh+ankle+bicep+forearm+wrist,
data = bodyfat_temp_all,
trControl = train,
method = 'lm',
na.action = na.pass)
model_caret

```




### Filtered var

```{r}
lambda_seq <- 10^seq(-3, 0, by = .1)
cv_object <- cv.glmnet(as.matrix(bodyfat_temp[,-1]), bodyfat_temp$bodyfat_brozek, lambda = lambda_seq, 
nfolds = 5)
cv_object

tibble(lambda = cv_object$lambda,
mean_cv_error = cv_object$cvm) %>%
ggplot(aes(x = lambda, y = 
mean_cv_error)) +
geom_point()
cv_object$lambda.min
```


```{r}
fit_bestcv <- glmnet(as.matrix(bodyfat_temp[,-1]), bodyfat_temp$bodyfat_brozek, lambda = cv_object$lambda.min)
best_lambda = cv_object$lambda.min
coef(fit_bestcv)
```


```{r}
set.seed(100)
# Use 5-fold validation and create the training sets
train = trainControl(method = "cv", number = 5)
# Fit the variables model 
model_caret = train(bodyfat_brozek ~ age + height + neck + chest+hip+thigh+forearm+wrist,
data = bodyfat_temp,
trControl = train,
method = 'lm',
na.action = na.pass)
model_caret
```






### Appendix 9 GLM

```{r}
myglm1 = glm(bodyfat_brozek~., data = bodyfat_temp,family=gaussian)
stepsearch_glm1 = step(myglm1)

Guassian_opt_glm = glm(formula = bodyfat_brozek ~ age + height + neck + chest + hip + thigh + 
    forearm + wrist, family = gaussian, data = bodyfat_temp)

plot(Guassian_opt_glm)
summary(Guassian_opt_glm)

```

